name: compas_fab
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - compas >= 2.0.4, < 3
  - compas_robots >= 0.3, < 1
  - roslibpy >= 1.1, < 2
  - pyserial
  - pybullet
  - pip:
      - -r requirements-dev.txt
      - -e .
