version: '2'
services:
  ros-master:
    image: gramaziokohler/ros-base:19.11
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-panda-planner:19.11
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: gramaziokohler/ros-panda-planner:19.11
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  panda-tf-panda_link0:
    image: gramaziokohler/ros-panda-planner:19.11
    container_name: panda-tf-panda_link0
    environment:
      - ROS_HOSTNAME=panda-tf-panda_link0
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - rosrun
      - tf
      - static_transform_publisher
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '1'
      - world
      - panda_link0
      - '100'

  panda-demo:
    image: gramaziokohler/ros-panda-planner:19.11
    container_name: panda-demo
    environment:
      - ROS_HOSTNAME=panda-demo
      - ROS_MASTER_URI=http://ros-master:11311
      - DISPLAY=gui:0.0
    depends_on:
      - ros-master
      - gui
    command:
      - roslaunch
      - --wait
      - panda_moveit_config
      - demo.launch

  gui:
    image: gramaziokohler/novnc:latest
    ports:
      - "8080:8080"
