name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.pull_request.labels.*.name, 'docs-only')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.9', '3.13']

    steps:
      - uses: compas-dev/compas-actions.build@v5
        env:
          CFLAGS: ${{ startsWith(matrix.os, 'macos') && '-fno-define-target-os-macros' || '' }}
        with:
          python: ${{ matrix.python }}
          invoke_lint: true
