name: docs

on:
  push:
    branches:
      - main
      - 'compas-2.x-compat'
  pull_request:
    branches:
      - main
      - 'compas-2.x-compat'

jobs:
  docs:
    name: build_docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install cython --config-settings="--build-option=--no-cython-compile"
      - name: Install
        run: |
          python -m pip install --no-cache-dir -r requirements-dev.txt
      - name: 📃 Generate docs
        if: success()
        run: |
          invoke docs --check-links
